#!/bin/bash

# Install things if any of them missing
echo "Checking if all convenience programs are installed..."
# Also curl, because we use that in this script
pkgs=(zsh nano tmux htop tree curl)
for pkg in "${pkgs[@]}"; do
	if ! command -v "$pkg" >/dev/null; then
		sudo apt install ${pkgs[@]}
		break
	fi
done

echo "Checking if all fancy zsh plugins are installed..."

# First! Oh My Zsh...
if [[ ! -d $HOME/.oh-my-zsh ]]; then
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
fi

# mcfly is a special kid
if ! command -v mcfly >/dev/null; then
	curl -LSfs https://raw.githubusercontent.com/cantino/mcfly/master/ci/install.sh | sudo sh -s -- --git cantino/mcfly
fi


# install some other plugins (Thanks MikeTTh)
plugs=(zsh-history-substring-search zsh-autosuggestions zsh-syntax-highlighting)
ZSH_CUSTOM="$HOME/.zsh_custom"
for plug in "${plugs[@]}"; do
	repo="https://github.com/zsh-users/$plug"
	folder="${ZSH_CUSTOM}/plugins/$plug"
	[[ -d "$folder" ]] || git clone "$repo" "$folder"
done

echo "Checking if ZSH is the login shell"

[[ $SHELL == $(which zsh) ]] || chsh -s $(which zsh)

echo "Checking for ssh key specific to this machine..."

# Generate ssh key if needed
if [[ ! -f "$HOME/.ssh/id_rsa" ]]; then
	hostname="${HOST:-$HOSTNAME}"
	ssh-keygen -b 4096 -t rsa -C "$USER@$hostname" -f ~/.ssh/id_rsa

	echo "Your new very own public key is the following:"
	echo
	cat ~/.ssh/id_rsa.pub
	echo
fi

echo "Installing crontab..."

while read line; do

	if ! crontab -l 2>/dev/null | grep -xFq "${line}"; then
		(crontab -l 2>/dev/null; echo "${line}") | crontab -
	fi

done << __EOF__
0 */2 * * * find $HOME/Downloads/ -mindepth 1 -mtime +7 -delete >/dev/null
15 */2 * * * $HOME/.local/bin/updatesshkeys >/dev/null
__EOF__


echo "Updating yadm origin url..."

# Change yadm origin address to use ssh
yadm remote set-url origin "git@github.com:marcsello/home.git"

echo "Updating public keys..."
$HOME/.local/bin/updatesshkeys
